### ISSUE TITLE
Node version v10.19.0 - Cannot read property '1' of null

### ISSUE THREAD

**Issue by jmowlaei** [yorkie/node-ifconfig#2]
TypeError: Cannot read property '1' of null
    at ..../node_modules/ifconfig-parser/index.js:51:24
    at Array.map (<anonymous>)
    at parse (....../node_modules/ifconfig-parser/index.js:42:17)
    at ......./node_modules/ifconfig/index.js:10:22
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)

**Comment by yorkie** [comment]
Could you please show me your `ifconfig` command result? It seems to be broken at https://github.com/yorkie/node-ifconfig-parser/blob/master/index.js#L51, where the MTU is missing.
